#include "Music.h"

// Cari amici followers, buonasera.
// È il 10/02/2026, ore 18:04. Ho avuto una brillante idea.
// Stavo pensando, ma se nel menù, muovendo lo switch, si sentisse una musichetta?
// Bella idea. Lo mettiamo SUBITO. La musichetta è la prima sigla di un caro anime, Your Lie in April.
// È stata così significativa che si merita un posto in questo lavoro, con la speranza che in futuro rimarrà a scuola
// e qualcuno riconoscerà la musichetta.
// Vado a registrare le note al pianoforte, a dopo!
// ...
// 1 ora dopo, tutto funziona! Dovevo lasciare un mio marchio musicale :)
// ~ Christian
namespace MenuData {
    const inline int numberOfNotes = 244;

    // Your Lie in April!!!
    const int menuMusic[numberOfNotes] = {
        NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_A5, NOTE_B5, NOTE_D6, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_FS5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_A5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_A5, NOTE_CS6, NOTE_D6, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_A5, NOTE_GS5, NOTE_FS5, NOTE_D5, NOTE_E5, NOTE_FS5, NOTE_A5, NOTE_GS5, NOTE_FS5, NOTE_GS5, NOTE_A5, NOTE_A6, NOTE_GS6, NOTE_A6, NOTE_E6, NOTE_D6, NOTE_CS6, NOTE_A5, NOTE_A4, NOTE_CS5, NOTE_D5, NOTE_E5, NOTE_E5, NOTE_D5, NOTE_CS5, NOTE_A4, NOTE_B4, NOTE_GS4, NOTE_B4, NOTE_CS5, NOTE_D5, NOTE_D5, NOTE_CS5, NOTE_B4, NOTE_GS4, NOTE_A4, NOTE_A4, NOTE_FS5, NOTE_E5, NOTE_D5, NOTE_CS5, NOTE_B4, NOTE_B4, NOTE_CS5, NOTE_CS5, NOTE_FS6, NOTE_E6, NOTE_D6, NOTE_CS6, NOTE_D6, NOTE_D5, NOTE_D5, NOTE_D5, NOTE_CS5, NOTE_B4, NOTE_A4, NOTE_B4, NOTE_E5, NOTE_D5, NOTE_E5, NOTE_A5, NOTE_CS5, NOTE_B4, NOTE_A4, NOTE_D5, NOTE_CS5, NOTE_B4, NOTE_A4, NOTE_A4, NOTE_CS5, NOTE_D5, NOTE_B4, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_A4, NOTE_A4, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_A4, NOTE_A4, NOTE_B4, NOTE_CS5, NOTE_B4, NOTE_B4, NOTE_A4, NOTE_B4, NOTE_A4, NOTE_CS5, NOTE_D5, NOTE_E5, NOTE_FS5, NOTE_GS5, NOTE_FS5, NOTE_F5, NOTE_FS5, NOTE_GS5, NOTE_CS5, NOTE_F5, NOTE_GS5, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_E5, NOTE_E5, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_A5, NOTE_B5, NOTE_CS6, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_E5, NOTE_E5, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_CS6, NOTE_CS6, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_FS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_E5, NOTE_E5, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_E5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_E6, NOTE_D6, NOTE_CS6, NOTE_CS6, NOTE_CS6, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_B5, NOTE_CS6, NOTE_D6, NOTE_CS6, NOTE_E5, NOTE_CS6, NOTE_CS6, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_FS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_GS5, NOTE_FS5, NOTE_E5, NOTE_E5, NOTE_E5, NOTE_CS5, NOTE_FS5, NOTE_E5, NOTE_E5, NOTE_CS5, NOTE_FS5, NOTE_FS5, NOTE_GS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_GS5, NOTE_A5, NOTE_B5, NOTE_CS6, NOTE_CS6, NOTE_CS6, NOTE_B5, NOTE_A5, NOTE_GS5, NOTE_FS5
    };
}